/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spalsh.screen;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        this.setExtendedState(Beranda.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        Tombol5 = new javax.swing.JPanel();
        anaktombol5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Tombol4 = new javax.swing.JPanel();
        anaktombol4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Tombol3 = new javax.swing.JPanel();
        anaktombol3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Tombol1 = new javax.swing.JPanel();
        anaktombol1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Tombol2 = new javax.swing.JPanel();
        anaktombol2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelAtas = new javax.swing.JPanel();
        Menu = new javax.swing.JTabbedPane();
        Panjang = new javax.swing.JPanel();
        cmtom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Luas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Volume = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Waktu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Suhu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmkem = new javax.swing.JPanel();
        CM = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        meter = new javax.swing.JTextField();
        sentimeter = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(12, 26, 50));
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(0, 153, 153));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tombol5.setBackground(new java.awt.Color(0, 153, 153));
        Tombol5.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol5MousePressed(evt);
            }
        });
        Tombol5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol5Layout = new javax.swing.GroupLayout(anaktombol5);
        anaktombol5.setLayout(anaktombol5Layout);
        anaktombol5Layout.setHorizontalGroup(
            anaktombol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol5Layout.setVerticalGroup(
            anaktombol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol5.add(anaktombol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Satuan Suhu");
        Tombol5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 30));

        panel_menu.add(Tombol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 280, -1));

        Tombol4.setBackground(new java.awt.Color(0, 153, 153));
        Tombol4.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol4MousePressed(evt);
            }
        });
        Tombol4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol4Layout = new javax.swing.GroupLayout(anaktombol4);
        anaktombol4.setLayout(anaktombol4Layout);
        anaktombol4Layout.setHorizontalGroup(
            anaktombol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol4Layout.setVerticalGroup(
            anaktombol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol4.add(anaktombol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Satuan Waktu");
        Tombol4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 30));

        panel_menu.add(Tombol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 280, -1));

        Tombol3.setBackground(new java.awt.Color(0, 153, 153));
        Tombol3.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol3MousePressed(evt);
            }
        });
        Tombol3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol3Layout = new javax.swing.GroupLayout(anaktombol3);
        anaktombol3.setLayout(anaktombol3Layout);
        anaktombol3Layout.setHorizontalGroup(
            anaktombol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol3Layout.setVerticalGroup(
            anaktombol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol3.add(anaktombol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Satuan Volume");
        Tombol3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 30));

        panel_menu.add(Tombol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 280, -1));

        Tombol1.setBackground(new java.awt.Color(0, 220, 190));
        Tombol1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol1MousePressed(evt);
            }
        });
        Tombol1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anaktombol1.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout anaktombol1Layout = new javax.swing.GroupLayout(anaktombol1);
        anaktombol1.setLayout(anaktombol1Layout);
        anaktombol1Layout.setHorizontalGroup(
            anaktombol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol1Layout.setVerticalGroup(
            anaktombol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol1.add(anaktombol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Satuan Panjang");
        Tombol1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 30));

        panel_menu.add(Tombol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 60));

        Tombol2.setBackground(new java.awt.Color(0, 153, 153));
        Tombol2.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol2MousePressed(evt);
            }
        });
        Tombol2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol2Layout = new javax.swing.GroupLayout(anaktombol2);
        anaktombol2.setLayout(anaktombol2Layout);
        anaktombol2Layout.setHorizontalGroup(
            anaktombol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol2Layout.setVerticalGroup(
            anaktombol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol2.add(anaktombol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Satuan Luas");
        Tombol2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 160, 30));

        panel_menu.add(Tombol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 280, -1));

        menu.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("Konversi");
        panel_menu.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\OOP\\coba3.png")); // NOI18N
        jLabel6.setText("jLabel6");
        panel_menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 980));

        Background.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -7, 280, 980));

        PanelAtas.setBackground(new java.awt.Color(13, 28, 53));
        PanelAtas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(PanelAtas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1920, 180));

        Panjang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmtom.setText("cm><m");
        cmtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmtomActionPerformed(evt);
            }
        });
        Panjang.add(cmtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel1.setText("Panjang");
        Panjang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 75, 337, 204));

        Menu.addTab("tab1", Panjang);

        jLabel2.setText("Luas");

        javax.swing.GroupLayout LuasLayout = new javax.swing.GroupLayout(Luas);
        Luas.setLayout(LuasLayout);
        LuasLayout.setHorizontalGroup(
            LuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addContainerGap(1524, Short.MAX_VALUE))
        );
        LuasLayout.setVerticalGroup(
            LuasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LuasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(751, Short.MAX_VALUE))
        );

        Menu.addTab("tab2", Luas);

        jLabel3.setText("Volume");

        javax.swing.GroupLayout VolumeLayout = new javax.swing.GroupLayout(Volume);
        Volume.setLayout(VolumeLayout);
        VolumeLayout.setHorizontalGroup(
            VolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(1550, Short.MAX_VALUE))
        );
        VolumeLayout.setVerticalGroup(
            VolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(751, Short.MAX_VALUE))
        );

        Menu.addTab("tab3", Volume);

        jLabel4.setText("waktu");

        javax.swing.GroupLayout WaktuLayout = new javax.swing.GroupLayout(Waktu);
        Waktu.setLayout(WaktuLayout);
        WaktuLayout.setHorizontalGroup(
            WaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaktuLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4)
                .addContainerGap(1351, Short.MAX_VALUE))
        );
        WaktuLayout.setVerticalGroup(
            WaktuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaktuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(751, Short.MAX_VALUE))
        );

        Menu.addTab("tab4", Waktu);

        jLabel5.setText("Suhu");

        javax.swing.GroupLayout SuhuLayout = new javax.swing.GroupLayout(Suhu);
        Suhu.setLayout(SuhuLayout);
        SuhuLayout.setHorizontalGroup(
            SuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuhuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(1564, Short.MAX_VALUE))
        );
        SuhuLayout.setVerticalGroup(
            SuhuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuhuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(751, Short.MAX_VALUE))
        );

        Menu.addTab("tab5", Suhu);

        cmkem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CM.setText("cm");
        cmkem.add(CM, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 346, -1, -1));

        m.setText("m");
        cmkem.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 346, -1, -1));

        meter.setText("0");
        meter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterActionPerformed(evt);
            }
        });
        cmkem.add(meter, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 275, 103, -1));

        sentimeter.setText("0");
        sentimeter.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                sentimeterComponentAdded(evt);
            }
        });
        sentimeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentimeterActionPerformed(evt);
            }
        });
        cmkem.add(sentimeter, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 275, 103, -1));

        Menu.addTab("tab6", cmkem);

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 160, 1610, 810));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tombol1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol1MousePressed
        // TODO add your handling code here:
        SetColour(Tombol1);
        anaktombol1.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2,Tombol3,Tombol4,Tombol5},  new JPanel []{anaktombol2, anaktombol3, anaktombol4, anaktombol5});
        Menu.setSelectedIndex(0);
    }//GEN-LAST:event_Tombol1MousePressed

    private void Tombol2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol2MousePressed
        // TODO add your handling code here:
        SetColour(Tombol2);
        anaktombol2.setOpaque(true);
        ResetColour(new JPanel[]{Tombol1,Tombol3,Tombol4,Tombol5},  new JPanel []{anaktombol1, anaktombol3, anaktombol4, anaktombol5});
        Menu.setSelectedIndex(1);
    }//GEN-LAST:event_Tombol2MousePressed

    private void Tombol3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol3MousePressed
        // TODO add your handling code here:
        SetColour(Tombol3);
        anaktombol3.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2,Tombol1,Tombol4,Tombol5},  new JPanel []{anaktombol2, anaktombol1, anaktombol4, anaktombol5});
        Menu.setSelectedIndex(2);
    }//GEN-LAST:event_Tombol3MousePressed

    private void Tombol4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol4MousePressed
        // TODO add your handling code here:
        SetColour(Tombol4);
        anaktombol4.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2,Tombol3,Tombol1,Tombol5},  new JPanel []{anaktombol2, anaktombol3, anaktombol1, anaktombol5});
        Menu.setSelectedIndex(3);
    }//GEN-LAST:event_Tombol4MousePressed

    private void Tombol5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol5MousePressed
        // TODO add your handling code here:
        SetColour(Tombol5);
        anaktombol5.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2,Tombol3,Tombol4,Tombol1},  new JPanel []{anaktombol2, anaktombol3, anaktombol4, anaktombol1});
        Menu.setSelectedIndex(4);
    }//GEN-LAST:event_Tombol5MousePressed

    private void cmtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmtomActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(5);
    }//GEN-LAST:event_cmtomActionPerformed

    private void sentimeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentimeterActionPerformed
        // TODO add your handling code here:
        Float x = Float.parseFloat(sentimeter.getText());
        Float y = x/100;
        meter.setText(String.valueOf(y));
    }//GEN-LAST:event_sentimeterActionPerformed

    private void sentimeterComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_sentimeterComponentAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sentimeterComponentAdded

    private void meterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterActionPerformed
        
        Integer z = Integer.parseInt(meter.getText());
        Integer w = z*100;
        sentimeter.setText(String.valueOf(w));        // TODO add your handling code here:
    }//GEN-LAST:event_meterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }
    private void SetColour(JPanel pane){
        pane.setBackground(new Color(0, 220, 190));
        
    }
    private void ResetColour(JPanel [] pane, JPanel [] Indikator){
        for(int i=0; i<pane.length; i++){
         pane[i].setBackground(new Color(0, 153, 153));
        }
        for(int i=0; i<Indikator.length; i++){
         Indikator[i].setOpaque(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel CM;
    private javax.swing.JPanel Luas;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JPanel PanelAtas;
    private javax.swing.JPanel Panjang;
    private javax.swing.JPanel Suhu;
    private javax.swing.JPanel Tombol1;
    private javax.swing.JPanel Tombol2;
    private javax.swing.JPanel Tombol3;
    private javax.swing.JPanel Tombol4;
    private javax.swing.JPanel Tombol5;
    private javax.swing.JPanel Volume;
    private javax.swing.JPanel Waktu;
    private javax.swing.JPanel anaktombol1;
    private javax.swing.JPanel anaktombol2;
    private javax.swing.JPanel anaktombol3;
    private javax.swing.JPanel anaktombol4;
    private javax.swing.JPanel anaktombol5;
    private javax.swing.JPanel cmkem;
    private javax.swing.JButton cmtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel m;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField meter;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JTextField sentimeter;
    // End of variables declaration//GEN-END:variables
}
