/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spalsh.screen;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Berandayj
     */
    public Beranda() {
        initComponents();
        this.setExtendedState(Beranda.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        Tombol5 = new javax.swing.JPanel();
        anaktombol5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Tombol4 = new javax.swing.JPanel();
        anaktombol4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Tombol3 = new javax.swing.JPanel();
        anaktombol3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Tombol1 = new javax.swing.JPanel();
        anaktombol1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Tombol2 = new javax.swing.JPanel();
        anaktombol2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelAtas = new javax.swing.JPanel();
        Menu = new javax.swing.JTabbedPane();
        Panjang = new javax.swing.JPanel();
        Dm = new javax.swing.JTextField();
        Km = new javax.swing.JTextField();
        Hm = new javax.swing.JTextField();
        Dam = new javax.swing.JTextField();
        M = new javax.swing.JTextField();
        MM = new javax.swing.JTextField();
        Cm = new javax.swing.JTextField();
        km = new javax.swing.JLabel();
        hm = new javax.swing.JLabel();
        mm = new javax.swing.JLabel();
        dam = new javax.swing.JLabel();
        cm1 = new javax.swing.JLabel();
        dm = new javax.swing.JLabel();
        dm1 = new javax.swing.JLabel();
        bekgron = new javax.swing.JLabel();
        Luas = new javax.swing.JPanel();
        rante = new javax.swing.JTextField();
        ha = new javax.swing.JLabel();
        HA = new javax.swing.JTextField();
        meter = new javax.swing.JTextField();
        m1 = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bekgron1 = new javax.swing.JLabel();
        Volume = new javax.swing.JPanel();
        mL1 = new javax.swing.JLabel();
        meterkubik = new javax.swing.JTextField();
        mililiter = new javax.swing.JTextField();
        ha1 = new javax.swing.JLabel();
        liter = new javax.swing.JTextField();
        galon = new javax.swing.JTextField();
        mL = new javax.swing.JLabel();
        Liter = new javax.swing.JLabel();
        bekgron2 = new javax.swing.JLabel();
        Waktu = new javax.swing.JPanel();
        jam = new javax.swing.JTextField();
        ha3 = new javax.swing.JLabel();
        menit = new javax.swing.JTextField();
        m5 = new javax.swing.JLabel();
        detik = new javax.swing.JTextField();
        m6 = new javax.swing.JLabel();
        hari = new javax.swing.JTextField();
        m4 = new javax.swing.JLabel();
        minggu = new javax.swing.JTextField();
        ha2 = new javax.swing.JLabel();
        tahun = new javax.swing.JTextField();
        bulan = new javax.swing.JTextField();
        m2 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bekgron3 = new javax.swing.JLabel();
        Suhu = new javax.swing.JPanel();
        mL2 = new javax.swing.JLabel();
        meterkubik2 = new javax.swing.JTextField();
        mL4 = new javax.swing.JLabel();
        kelvin = new javax.swing.JTextField();
        Celcius = new javax.swing.JTextField();
        ha4 = new javax.swing.JLabel();
        fahreinheit = new javax.swing.JTextField();
        reamur = new javax.swing.JTextField();
        mL3 = new javax.swing.JLabel();
        Liter1 = new javax.swing.JLabel();
        bekgron4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(12, 26, 50));
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(0, 153, 153));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tombol5.setBackground(new java.awt.Color(0, 153, 153));
        Tombol5.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol5MousePressed(evt);
            }
        });
        Tombol5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol5Layout = new javax.swing.GroupLayout(anaktombol5);
        anaktombol5.setLayout(anaktombol5Layout);
        anaktombol5Layout.setHorizontalGroup(
            anaktombol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol5Layout.setVerticalGroup(
            anaktombol5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol5.add(anaktombol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Satuan Suhu");
        Tombol5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 30));

        panel_menu.add(Tombol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 290, -1));

        Tombol4.setBackground(new java.awt.Color(0, 153, 153));
        Tombol4.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol4MousePressed(evt);
            }
        });
        Tombol4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol4Layout = new javax.swing.GroupLayout(anaktombol4);
        anaktombol4.setLayout(anaktombol4Layout);
        anaktombol4Layout.setHorizontalGroup(
            anaktombol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol4Layout.setVerticalGroup(
            anaktombol4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol4.add(anaktombol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Satuan Waktu");
        Tombol4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 30));

        panel_menu.add(Tombol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 290, -1));

        Tombol3.setBackground(new java.awt.Color(0, 153, 153));
        Tombol3.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol3MousePressed(evt);
            }
        });
        Tombol3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol3Layout = new javax.swing.GroupLayout(anaktombol3);
        anaktombol3.setLayout(anaktombol3Layout);
        anaktombol3Layout.setHorizontalGroup(
            anaktombol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol3Layout.setVerticalGroup(
            anaktombol3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol3.add(anaktombol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Satuan Volume");
        Tombol3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 30));

        panel_menu.add(Tombol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 290, -1));

        Tombol1.setBackground(new java.awt.Color(0, 220, 190));
        Tombol1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol1MousePressed(evt);
            }
        });
        Tombol1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        anaktombol1.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout anaktombol1Layout = new javax.swing.GroupLayout(anaktombol1);
        anaktombol1.setLayout(anaktombol1Layout);
        anaktombol1Layout.setHorizontalGroup(
            anaktombol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol1Layout.setVerticalGroup(
            anaktombol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol1.add(anaktombol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Satuan Panjang");
        Tombol1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 160, 30));

        panel_menu.add(Tombol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 290, 60));

        Tombol2.setBackground(new java.awt.Color(0, 153, 153));
        Tombol2.setPreferredSize(new java.awt.Dimension(270, 60));
        Tombol2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tombol2MousePressed(evt);
            }
        });
        Tombol2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout anaktombol2Layout = new javax.swing.GroupLayout(anaktombol2);
        anaktombol2.setLayout(anaktombol2Layout);
        anaktombol2Layout.setHorizontalGroup(
            anaktombol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        anaktombol2Layout.setVerticalGroup(
            anaktombol2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Tombol2.add(anaktombol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Satuan Luas");
        Tombol2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 160, 30));

        panel_menu.add(Tombol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 290, -1));

        menu.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("Konversi");
        panel_menu.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/coba3.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        panel_menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 980));

        Background.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -7, 290, 980));

        PanelAtas.setBackground(new java.awt.Color(13, 28, 53));
        PanelAtas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(PanelAtas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1920, 180));

        Panjang.setBackground(new java.awt.Color(0, 220, 190));
        Panjang.setForeground(new java.awt.Color(255, 255, 255));
        Panjang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Dm.setText("0");
        Dm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DmKeyReleased(evt);
            }
        });
        Panjang.add(Dm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 150, 50));

        Km.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Km.setText("0");
        Km.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KmKeyReleased(evt);
            }
        });
        Panjang.add(Km, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 150, 50));

        Hm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hm.setText("0");
        Hm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HmKeyReleased(evt);
            }
        });
        Panjang.add(Hm, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 150, 50));

        Dam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Dam.setText("0");
        Dam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DamKeyReleased(evt);
            }
        });
        Panjang.add(Dam, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 150, 50));

        M.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        M.setText("0");
        M.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MKeyReleased(evt);
            }
        });
        Panjang.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 290, 150, 50));

        MM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MM.setText("0");
        MM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MMKeyReleased(evt);
            }
        });
        Panjang.add(MM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 550, 150, 50));

        Cm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cm.setText("0");
        Cm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CmKeyReleased(evt);
            }
        });
        Panjang.add(Cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 150, 50));

        km.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        km.setForeground(new java.awt.Color(51, 51, 0));
        km.setText("Km");
        Panjang.add(km, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        hm.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        hm.setForeground(new java.awt.Color(51, 51, 0));
        hm.setText("Hm");
        Panjang.add(hm, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        mm.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        mm.setForeground(new java.awt.Color(51, 51, 0));
        mm.setText("mm");
        Panjang.add(mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, -1, -1));

        dam.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        dam.setForeground(new java.awt.Color(51, 51, 0));
        dam.setText("Dam");
        Panjang.add(dam, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, -1, -1));

        cm1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        cm1.setForeground(new java.awt.Color(51, 51, 0));
        cm1.setText("Cm");
        Panjang.add(cm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, -1, -1));

        dm.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        dm.setForeground(new java.awt.Color(51, 51, 0));
        dm.setText("M");
        Panjang.add(dm, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 330, -1, -1));

        dm1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        dm1.setForeground(new java.awt.Color(51, 51, 0));
        dm1.setText("Dm");
        Panjang.add(dm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        bekgron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/background1.png"))); // NOI18N
        bekgron.setText("jLabel1");
        Panjang.add(bekgron, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, -1, -1));

        Menu.addTab("tab1", Panjang);

        Luas.setBackground(new java.awt.Color(0, 220, 190));
        Luas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rante.setText("0");
        rante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ranteKeyReleased(evt);
            }
        });
        Luas.add(rante, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 150, 50));

        ha.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        ha.setForeground(new java.awt.Color(51, 51, 0));
        ha.setText("Ha");
        Luas.add(ha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        HA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HA.setText("0");
        HA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HAKeyReleased(evt);
            }
        });
        Luas.add(HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 150, 50));

        meter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        meter.setText("0");
        meter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                meterKeyReleased(evt);
            }
        });
        Luas.add(meter, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 150, 50));

        m1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        m1.setForeground(new java.awt.Color(51, 51, 0));
        m1.setText("Rante");
        Luas.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 150, -1));

        m.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        m.setForeground(new java.awt.Color(51, 51, 0));
        m.setText("m^2");
        Luas.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jLabel2.setText("Luas");
        Luas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 2443, -1, -1));

        bekgron1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/background1.png"))); // NOI18N
        bekgron1.setText("jLabel1");
        Luas.add(bekgron1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, -1, -1));

        Menu.addTab("tab2", Luas);

        Volume.setBackground(new java.awt.Color(0, 220, 190));
        Volume.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mL1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        mL1.setForeground(new java.awt.Color(51, 51, 0));
        mL1.setText("m^3");
        Volume.add(mL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 340, 140, -1));

        meterkubik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        meterkubik.setText("0");
        meterkubik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                meterkubikKeyReleased(evt);
            }
        });
        Volume.add(meterkubik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 290, 150, 50));

        mililiter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mililiter.setText("0");
        mililiter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mililiterKeyReleased(evt);
            }
        });
        Volume.add(mililiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 150, 50));

        ha1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        ha1.setForeground(new java.awt.Color(51, 51, 0));
        ha1.setText("Galon");
        Volume.add(ha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        liter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        liter.setText("0");
        liter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                literKeyReleased(evt);
            }
        });
        Volume.add(liter, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 150, 50));

        galon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        galon.setText("0");
        galon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                galonKeyReleased(evt);
            }
        });
        Volume.add(galon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 150, 50));

        mL.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        mL.setForeground(new java.awt.Color(51, 51, 0));
        mL.setText("mL");
        Volume.add(mL, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 80, -1));

        Liter.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        Liter.setForeground(new java.awt.Color(51, 51, 0));
        Liter.setText("Liter");
        Volume.add(Liter, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        bekgron2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/background1.png"))); // NOI18N
        bekgron2.setText("jLabel1");
        Volume.add(bekgron2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, -1, -1));

        Menu.addTab("tab3", Volume);

        Waktu.setBackground(new java.awt.Color(0, 220, 190));
        Waktu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jam.setText("0");
        jam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jamKeyReleased(evt);
            }
        });
        Waktu.add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 150, 50));

        ha3.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        ha3.setForeground(new java.awt.Color(51, 51, 0));
        ha3.setText("Jam");
        Waktu.add(ha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        menit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        menit.setText("0");
        menit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menitKeyReleased(evt);
            }
        });
        Waktu.add(menit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 150, 50));

        m5.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        m5.setForeground(new java.awt.Color(51, 51, 0));
        m5.setText("Menit");
        Waktu.add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, -1, -1));

        detik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        detik.setText("0");
        detik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                detikKeyReleased(evt);
            }
        });
        Waktu.add(detik, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 520, 150, 50));

        m6.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        m6.setForeground(new java.awt.Color(51, 51, 0));
        m6.setText("Detik");
        Waktu.add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 190, -1));

        hari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hari.setText("0");
        hari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hariKeyReleased(evt);
            }
        });
        Waktu.add(hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 280, 150, 50));

        m4.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        m4.setForeground(new java.awt.Color(51, 51, 0));
        m4.setText("Hari");
        Waktu.add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 320, 190, -1));

        minggu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minggu.setText("0");
        minggu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mingguKeyReleased(evt);
            }
        });
        Waktu.add(minggu, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 150, 50));

        ha2.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        ha2.setForeground(new java.awt.Color(51, 51, 0));
        ha2.setText("Tahun");
        Waktu.add(ha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        tahun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tahun.setText("0");
        tahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tahunKeyReleased(evt);
            }
        });
        Waktu.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 150, 50));

        bulan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bulan.setText("0");
        bulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bulanKeyReleased(evt);
            }
        });
        Waktu.add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 150, 50));

        m2.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        m2.setForeground(new java.awt.Color(51, 51, 0));
        m2.setText("Minggu");
        Waktu.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 190, -1));

        m3.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        m3.setForeground(new java.awt.Color(51, 51, 0));
        m3.setText("Bulan");
        Waktu.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel3.setText("Luas");
        Waktu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 2443, -1, -1));

        bekgron3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/background1.png"))); // NOI18N
        bekgron3.setText("jLabel1");
        Waktu.add(bekgron3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, -1, -1));

        Menu.addTab("tab4", Waktu);

        Suhu.setBackground(new java.awt.Color(0, 220, 190));
        Suhu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mL2.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        mL2.setForeground(new java.awt.Color(51, 51, 0));
        mL2.setText("Kelvin");
        Suhu.add(mL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 190, -1));

        meterkubik2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        meterkubik2.setText("0");
        meterkubik2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                meterkubik2KeyReleased(evt);
            }
        });
        Suhu.add(meterkubik2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 150, 50));

        mL4.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        mL4.setForeground(new java.awt.Color(51, 51, 0));
        mL4.setText("m^3");
        Suhu.add(mL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 540, 140, -1));

        kelvin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kelvin.setText("0");
        kelvin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kelvinKeyReleased(evt);
            }
        });
        Suhu.add(kelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 150, 50));

        Celcius.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Celcius.setText("0");
        Celcius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CelciusKeyReleased(evt);
            }
        });
        Suhu.add(Celcius, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 230, 150, 50));

        ha4.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        ha4.setForeground(new java.awt.Color(51, 51, 0));
        ha4.setText("Reamur");
        Suhu.add(ha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        fahreinheit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fahreinheit.setText("0");
        fahreinheit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fahreinheitKeyReleased(evt);
            }
        });
        Suhu.add(fahreinheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 150, 50));

        reamur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reamur.setText("0");
        reamur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reamurKeyReleased(evt);
            }
        });
        Suhu.add(reamur, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, 50));

        mL3.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        mL3.setForeground(new java.awt.Color(51, 51, 0));
        mL3.setText("Celcius");
        Suhu.add(mL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 270, 210, -1));

        Liter1.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        Liter1.setForeground(new java.awt.Color(51, 51, 0));
        Liter1.setText("Fahreinheit");
        Suhu.add(Liter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        bekgron4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SplashScreen/Assets/background1.png"))); // NOI18N
        bekgron4.setText("jLabel1");
        Suhu.add(bekgron4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, -1, -1));

        Menu.addTab("tab5", Suhu);

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 160, 1630, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1932, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tombol1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol1MousePressed
        // TODO add your handling code here:
        SetColour(Tombol1);
        anaktombol1.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2, Tombol3, Tombol4, Tombol5}, new JPanel[]{anaktombol2, anaktombol3, anaktombol4, anaktombol5});
        Menu.setSelectedIndex(0);
    }//GEN-LAST:event_Tombol1MousePressed

    private void Tombol2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol2MousePressed
        // TODO add your handling code here:
        SetColour(Tombol2);
        anaktombol2.setOpaque(true);
        ResetColour(new JPanel[]{Tombol1, Tombol3, Tombol4, Tombol5}, new JPanel[]{anaktombol1, anaktombol3, anaktombol4, anaktombol5});
        Menu.setSelectedIndex(1);
    }//GEN-LAST:event_Tombol2MousePressed

    private void Tombol3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol3MousePressed
        // TODO add your handling code here:
        SetColour(Tombol3);
        anaktombol3.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2, Tombol1, Tombol4, Tombol5}, new JPanel[]{anaktombol2, anaktombol1, anaktombol4, anaktombol5});
        Menu.setSelectedIndex(2);
    }//GEN-LAST:event_Tombol3MousePressed

    private void Tombol4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol4MousePressed
        // TODO add your handling code here:
        SetColour(Tombol4);
        anaktombol4.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2, Tombol3, Tombol1, Tombol5}, new JPanel[]{anaktombol2, anaktombol3, anaktombol1, anaktombol5});
        Menu.setSelectedIndex(3);
    }//GEN-LAST:event_Tombol4MousePressed

    private void Tombol5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tombol5MousePressed
        // TODO add your handling code here:
        SetColour(Tombol5);
        anaktombol5.setOpaque(true);
        ResetColour(new JPanel[]{Tombol2, Tombol3, Tombol4, Tombol1}, new JPanel[]{anaktombol2, anaktombol3, anaktombol4, anaktombol1});
        Menu.setSelectedIndex(4);
    }//GEN-LAST:event_Tombol5MousePressed

    private void DamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DamKeyReleased
        float i = Float.valueOf(Dam.getText());
        float nilaihm = i / 10;
        float nilaikm = i / 100;
        float nilaim = i * 10;
        float nilaidm = i * 100;
        float nilaicm = i * 1000;
        float nilaimm = i * 10000;
        Hm.setText(String.valueOf(nilaihm));
        Km.setText(String.valueOf(nilaikm));
        M.setText(String.valueOf(nilaim));
        Dm.setText(String.valueOf(nilaidm));
        Cm.setText(String.valueOf(nilaicm));
        MM.setText(String.valueOf(nilaimm));
    }//GEN-LAST:event_DamKeyReleased

    private void KmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KmKeyReleased
        float i = Float.valueOf(Km.getText());
        float nilaihm = i * 10;
        float nilaidam = i * 100;
        float nilaim = i * 1000;
        float nilaidm = i * 10000;
        float nilaicm = i * 100000;
        float nilaimm = i * 1000000;
        Hm.setText(String.valueOf(nilaihm));
        Dam.setText(String.valueOf(nilaidam));
        M.setText(String.valueOf(nilaim));
        Dm.setText(String.valueOf(nilaidm));
        Cm.setText(String.valueOf(nilaicm));
        MM.setText(String.valueOf(nilaimm));
    }//GEN-LAST:event_KmKeyReleased

    private void HmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HmKeyReleased
        float i = Float.parseFloat(Hm.getText());
        float nilaikm = i / 10;
        float nilaidam = i * 10;
        float nilaim = i * 100;
        float nilaidm = i * 1000;
        float nilaicm = i * 10000;
        float nilaimm = i * 100000;
        Km.setText(String.valueOf(nilaikm));
        Dam.setText(String.valueOf(nilaidam));
        M.setText(String.valueOf(nilaim));
        Dm.setText(String.valueOf(nilaidm));
        Cm.setText(String.valueOf(nilaicm));
        MM.setText(String.valueOf(nilaimm));
    }//GEN-LAST:event_HmKeyReleased

    private void MKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MKeyReleased
        float i = Float.parseFloat(M.getText());
        float nilaikm = i / 1000;
        float nilaidam = i / 10;
        float nilaihm = i / 100;
        float nilaidm = i * 10;
        float nilaicm = i * 100;
        float nilaimm = i * 1000;
        Km.setText(String.valueOf(nilaikm));
        Dam.setText(String.valueOf(nilaidam));
        Hm.setText(String.valueOf(nilaihm));
        Dm.setText(String.valueOf(nilaidm));
        Cm.setText(String.valueOf(nilaicm));
        MM.setText(String.valueOf(nilaimm));
    }//GEN-LAST:event_MKeyReleased

    private void DmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DmKeyReleased
        float i = Float.parseFloat(Dm.getText());
        float nilaikm = i / 10000;
        float nilaidam = i / 100;
        float nilaihm = i / 1000;
        float nilaim = i * 10;
        float nilaicm = i * 10;
        float nilaimm = i * 100;
        Km.setText(String.valueOf(nilaikm));
        Dam.setText(String.valueOf(nilaidam));
        Hm.setText(String.valueOf(nilaihm));
        M.setText(String.valueOf(nilaim));
        Cm.setText(String.valueOf(nilaicm));
        MM.setText(String.valueOf(nilaimm));
    }//GEN-LAST:event_DmKeyReleased

    private void CmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmKeyReleased
        float i = Float.parseFloat(Cm.getText());
        float nilaikm = i / 100000;
        float nilaidam = i / 1000;
        float nilaihm = i / 10000;
        float nilaim = i / 100;
        float nilaidm = i / 10;
        float nilaimm = i * 10;
        Km.setText(String.valueOf(nilaikm));
        Dam.setText(String.valueOf(nilaidam));
        Hm.setText(String.valueOf(nilaihm));
        M.setText(String.valueOf(nilaim));
        Dm.setText(String.valueOf(nilaidm));
        MM.setText(String.valueOf(nilaimm));
    }//GEN-LAST:event_CmKeyReleased

    private void MMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MMKeyReleased
        float i = Float.parseFloat(MM.getText());
        float nilaikm = i / 1000000;
        float nilaidam = i / 10000;
        float nilaihm = i / 100000;
        float nilaim = i / 1000;
        float nilaidm = i / 100;
        float nilaicm = i / 10;
        Km.setText(String.valueOf(nilaikm));
        Dam.setText(String.valueOf(nilaidam));
        Hm.setText(String.valueOf(nilaihm));
        M.setText(String.valueOf(nilaim));
        Dm.setText(String.valueOf(nilaidm));
        Cm.setText(String.valueOf(nilaicm));
    }//GEN-LAST:event_MMKeyReleased

    private void meterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meterKeyReleased
        float i = Float.parseFloat(meter.getText());
        float me = i / 10000;
        float ran = i / 400;
        HA.setText(String.valueOf(me));
        rante.setText(String.valueOf(ran));
    }//GEN-LAST:event_meterKeyReleased

    private void HAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HAKeyReleased
        float i = Float.parseFloat(HA.getText());
        float me = i * 10000;
        float ran = i * 25;
        meter.setText(String.valueOf(me));
        rante.setText(String.valueOf(ran));
    }//GEN-LAST:event_HAKeyReleased

    private void ranteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ranteKeyReleased
        float i = Float.parseFloat(rante.getText());
        float me = i * 400;
        float ran = i / 25;
        meter.setText(String.valueOf(me));
        HA.setText(String.valueOf(ran));
    }//GEN-LAST:event_ranteKeyReleased

    private void mililiterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mililiterKeyReleased
        float i = Float.parseFloat(mililiter.getText());
        float Ga = (float) (i / 3785.41);
        float l = i / 1000;
        float mkub = i / 1000000;
        galon.setText(String.valueOf(Ga));
        liter.setText(String.valueOf(l));
        meterkubik.setText(String.valueOf(mkub));
    }//GEN-LAST:event_mililiterKeyReleased

    private void literKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_literKeyReleased
        float i = Float.parseFloat(liter.getText());
        float Ga = (float) (i / 3.78541);
        float l = i * 1000;
        float mkub = i / 1000;
        galon.setText(String.valueOf(Ga));
        mililiter.setText(String.valueOf(l));
        meterkubik.setText(String.valueOf(mkub));
    }//GEN-LAST:event_literKeyReleased

    private void galonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_galonKeyReleased
        float i = Float.parseFloat(galon.getText());
        float Ga = (float) (i * 3.78541);
        float l = (float) (i * 3785.41);
        float mkub = (float) (i / 264.172);
        liter.setText(String.valueOf(Ga));
        mililiter.setText(String.valueOf(l));
        meterkubik.setText(String.valueOf(mkub));
    }//GEN-LAST:event_galonKeyReleased

    private void meterkubikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meterkubikKeyReleased
        float i = Float.parseFloat(meterkubik.getText());
        float Ga = i * 1000;
        float l = i * 1000000;
        float mkub = (float) (i * 264.172);
        liter.setText(String.valueOf(Ga));
        mililiter.setText(String.valueOf(l));
        galon.setText(String.valueOf(mkub));
    }//GEN-LAST:event_meterkubikKeyReleased

    private void mingguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mingguKeyReleased
        float i = Float.parseFloat(minggu.getText());
        float thn = i / 48;
        float bln = i / 4;
        float hr = i * 7;
        float jm = i * 7 * 24;
        float mnt = i * 7 * 24 * 60;
        float dtk = i * 7 * 24 * 60 * 60;
        tahun.setText(String.valueOf(thn));
        bulan.setText(String.valueOf(bln));
        hari.setText(String.valueOf(hr));
        jam.setText(String.valueOf(jm));
        menit.setText(String.valueOf(mnt));
        detik.setText(String.valueOf(dtk));
    }//GEN-LAST:event_mingguKeyReleased

    private void tahunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tahunKeyReleased
        float i = Float.parseFloat(tahun.getText());
        float bln = i * 12;
        float migg = i * 12 * 4;
        float hr = i * 365;
        float jm = i * 365 * 24;
        float mnt = i * 365 * 24 * 60;
        float dtk = i * 365 * 24 * 60 * 60;
        bulan.setText(String.valueOf(bln));
        minggu.setText(String.valueOf(migg));
        hari.setText(String.valueOf(hr));
        jam.setText(String.valueOf(jm));
        menit.setText(String.valueOf(mnt));
        detik.setText(String.valueOf(dtk));
    }//GEN-LAST:event_tahunKeyReleased

    private void bulanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bulanKeyReleased
        float i = Float.parseFloat(bulan.getText());
        float thn = i / 12;
        float migg = i * 4;
        float hr = i * 30;
        float jm = i * 30 * 24;
        float mnt = i * 30 * 24 * 60;
        float dtk = i * 30 * 24 * 60 * 60;
        tahun.setText(String.valueOf(thn));
        minggu.setText(String.valueOf(migg));
        hari.setText(String.valueOf(hr));
        jam.setText(String.valueOf(jm));
        menit.setText(String.valueOf(mnt));
        detik.setText(String.valueOf(dtk));
    }//GEN-LAST:event_bulanKeyReleased

    private void hariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hariKeyReleased
        float i = Float.parseFloat(hari.getText());
        float thn = i / 365;
        float bln = i / 30;
        float migg = i / 7;
        float jm = i * 24;
        float mnt = i * 24 * 60;
        float dtk = i * 24 * 60 * 60;
        tahun.setText(String.valueOf(thn));
        bulan.setText(String.valueOf(bln));
        minggu.setText(String.valueOf(migg));
        jam.setText(String.valueOf(jm));
        menit.setText(String.valueOf(mnt));
        detik.setText(String.valueOf(dtk));
    }//GEN-LAST:event_hariKeyReleased

    private void jamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jamKeyReleased
        float i = Float.parseFloat(jam.getText());
        float thn = i / 24 / 365;
        float bln = i / 24 / 30;
        float hr = i / 24;
        float migg = i / 24 / 7;
        float mnt = i * 60;
        float dtk = i * 60 * 60;
        tahun.setText(String.valueOf(thn));
        bulan.setText(String.valueOf(bln));
        hari.setText(String.valueOf(hr));
        minggu.setText(String.valueOf(migg));
        menit.setText(String.valueOf(mnt));
        detik.setText(String.valueOf(dtk));
    }//GEN-LAST:event_jamKeyReleased

    private void menitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menitKeyReleased
        float i = Float.parseFloat(menit.getText());
        float thn = i / 60 / 24 / 365;
        float bln = i / 60 / 24 / 30;
        float hr = i / 60 / 24;
        float migg = i / 60 / 24 / 7;
        float jm = i / 60;
        float dtk = i * 60;
        tahun.setText(String.valueOf(thn));
        bulan.setText(String.valueOf(bln));
        hari.setText(String.valueOf(hr));
        minggu.setText(String.valueOf(migg));
        jam.setText(String.valueOf(jm));
        detik.setText(String.valueOf(dtk));
    }//GEN-LAST:event_menitKeyReleased

    private void detikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detikKeyReleased
        float i = Float.parseFloat(detik.getText());
        float thn = i / 60 / 60 / 24 / 365;
        float bln = i / 60 / 60 / 24 / 30;
        float hr = i / 60 / 60 / 24;
        float migg = i / 60 / 60 / 24 / 7;
        float jm = i / 60 / 60;
        float mnt = i / 60;
        tahun.setText(String.valueOf(thn));
        bulan.setText(String.valueOf(bln));
        hari.setText(String.valueOf(hr));
        minggu.setText(String.valueOf(migg));
        jam.setText(String.valueOf(jm));
        menit.setText(String.valueOf(mnt));
    }//GEN-LAST:event_detikKeyReleased

    private void kelvinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kelvinKeyReleased
        float k = Float.parseFloat(kelvin.getText());
        float c = k - 273;
        float f = (k - 273) * (9 / 5) + 32;
        float r = (4 / 5) * (k - 273);
        Celcius.setText(String.valueOf(c));
        fahreinheit.setText(String.valueOf(f));
        reamur.setText(String.valueOf(r));
    }//GEN-LAST:event_kelvinKeyReleased

    private void CelciusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CelciusKeyReleased
        float c = Float.parseFloat(Celcius.getText());
        float k = c + 273;
        float f = (9 / 5) * (c + 32);
        float r = (4 / 5) * c;
        kelvin.setText(String.valueOf(k));
        fahreinheit.setText(String.valueOf(f));
        reamur.setText(String.valueOf(r));
    }//GEN-LAST:event_CelciusKeyReleased

    private void fahreinheitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fahreinheitKeyReleased
        float f = Float.parseFloat(fahreinheit.getText());
        float c = (5/9)*(f-32);
        float k = (5/ 9) * (f-32) +273;
        float r = (4 / 9) * (f-32);
        kelvin.setText(String.valueOf(k));
        fahreinheit.setText(String.valueOf(f));
        reamur.setText(String.valueOf(r));
    }//GEN-LAST:event_fahreinheitKeyReleased

    private void reamurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reamurKeyReleased
        float r = Float.parseFloat(reamur.getText());
        float c = (5 / 4) * r;
        float f = ((9 / 4) * r) + 32;
        float k = (4 / 5) * r * (300 - 273);
        Celcius.setText(String.valueOf(c));
        fahreinheit.setText(String.valueOf(f));
        kelvin.setText(String.valueOf(k));
    }//GEN-LAST:event_reamurKeyReleased

    private void meterkubik2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_meterkubik2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_meterkubik2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });

    }

    private void SetColour(JPanel pane) {
        pane.setBackground(new Color(0, 220, 190));

    }

    private void ResetColour(JPanel[] pane, JPanel[] Indikator) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(0, 153, 153));
        }
        for (int i = 0; i < Indikator.length; i++) {
            Indikator[i].setOpaque(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JTextField Celcius;
    private javax.swing.JTextField Cm;
    private javax.swing.JTextField Dam;
    private javax.swing.JTextField Dm;
    private javax.swing.JTextField HA;
    private javax.swing.JTextField Hm;
    private javax.swing.JTextField Km;
    private javax.swing.JLabel Liter;
    private javax.swing.JLabel Liter1;
    private javax.swing.JPanel Luas;
    private javax.swing.JTextField M;
    private javax.swing.JTextField MM;
    private javax.swing.JTabbedPane Menu;
    private javax.swing.JPanel PanelAtas;
    private javax.swing.JPanel Panjang;
    private javax.swing.JPanel Suhu;
    private javax.swing.JPanel Tombol1;
    private javax.swing.JPanel Tombol2;
    private javax.swing.JPanel Tombol3;
    private javax.swing.JPanel Tombol4;
    private javax.swing.JPanel Tombol5;
    private javax.swing.JPanel Volume;
    private javax.swing.JPanel Waktu;
    private javax.swing.JPanel anaktombol1;
    private javax.swing.JPanel anaktombol2;
    private javax.swing.JPanel anaktombol3;
    private javax.swing.JPanel anaktombol4;
    private javax.swing.JPanel anaktombol5;
    private javax.swing.JLabel bekgron;
    private javax.swing.JLabel bekgron1;
    private javax.swing.JLabel bekgron2;
    private javax.swing.JLabel bekgron3;
    private javax.swing.JLabel bekgron4;
    private javax.swing.JTextField bulan;
    private javax.swing.JLabel cm1;
    private javax.swing.JLabel dam;
    private javax.swing.JTextField detik;
    private javax.swing.JLabel dm;
    private javax.swing.JLabel dm1;
    private javax.swing.JTextField fahreinheit;
    private javax.swing.JTextField galon;
    private javax.swing.JLabel ha;
    private javax.swing.JLabel ha1;
    private javax.swing.JLabel ha2;
    private javax.swing.JLabel ha3;
    private javax.swing.JLabel ha4;
    private javax.swing.JTextField hari;
    private javax.swing.JLabel hm;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jam;
    private javax.swing.JTextField kelvin;
    private javax.swing.JLabel km;
    private javax.swing.JTextField liter;
    private javax.swing.JLabel m;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m4;
    private javax.swing.JLabel m5;
    private javax.swing.JLabel m6;
    private javax.swing.JLabel mL;
    private javax.swing.JLabel mL1;
    private javax.swing.JLabel mL2;
    private javax.swing.JLabel mL3;
    private javax.swing.JLabel mL4;
    private javax.swing.JTextField menit;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField meter;
    private javax.swing.JTextField meterkubik;
    private javax.swing.JTextField meterkubik2;
    private javax.swing.JTextField mililiter;
    private javax.swing.JTextField minggu;
    private javax.swing.JLabel mm;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JTextField rante;
    private javax.swing.JTextField reamur;
    private javax.swing.JTextField tahun;
    // End of variables declaration//GEN-END:variables
}
